### ISSUE TITLE
Referenced assembly 'Serilog.Sinks.Logz.Io, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

### ISSUE THREAD

**Issue by vehs-gallaux** [serilog-contrib/Serilog.Sinks.Http.LogzIo#19]
My exception handling project outputs a signed dll that's being used by a number of other solutions (disabling assembly signing is unfortunately not an available option). I'm running into the following error when attempting to build the project
> Referenced assembly 'Serilog.Sinks.Logz.Io, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

I've been forced to manually sign the assembly to get this to work but this is far from ideal. That applies to both Serilog.Sinks.Logz.Io and Serilog.Sinks.Http.LogzIo

**Comment by mantas-amberlo** [comment]
Will try to check this as soon as possible.

**Comment by mantasaudickas** [comment]
Will try to check this as soon as possible.

**Comment by mantasaudickas** [comment]
Assemblies are now signed.
Please check: 
https://www.nuget.org/packages/Serilog.Sinks.Logz.Io/5.0.0
https://www.nuget.org/packages/Serilog.Sinks.Http.LogzIo/2.0.0
