### ISSUE TITLE
Unoptimized assembly detected: 'Serilog.Sinks.Logz.Io.dll'

### ISSUE THREAD

**Issue by bruno-garcia** [serilog-contrib/Serilog.Sinks.Http.LogzIo#20]
While upgrading [NuGet Trends](https://github.com/dotnet/nuget-trends)'s package reference of `Serilog.Sinks.Logz.Io` from version  **2.2.2** to **3.0.1** [UnoptimizedAssemblyDetector](https://github.com/bruno-garcia/unoptimized-assembly-detector) alerted the DLL wasn't compiled with optimizations:

```
/Users/bruno/.nuget/packages/unoptimizedassemblydetector/0.1.1/build/UnoptimizedAssemblyDetector.targets(14,5): warning : Unoptimized assembly detected: 'Serilog.Sinks.Logz.Io.dll' at /Users/bruno/.nuget/packages/serilog.sinks.logz.io/3.0.1/lib/netstandard2.1/Serilog.Sinks.Logz.Io.dll [/Users/bruno/git/nuget-trends/src/NuGetTrends.Scheduler/NuGetTrends.Scheduler.csproj]
/Users/bruno/.nuget/packages/unoptimizedassemblydetector/0.1.1/build/UnoptimizedAssemblyDetector.targets(14,5): warning : Unoptimized assembly detected: 'Serilog.Sinks.Logz.Io.dll' at /Users/bruno/.nuget/packages/serilog.sinks.logz.io/3.0.1/lib/netstandard2.1/Serilog.Sinks.Logz.Io.dll [/Users/bruno/git/nuget-trends/src/NuGetTrends.Web/NuGetTrends.Web.csproj]
    2 Warning(s)
```

I don't see an automation in the repo to review, but is it possible packaging was done without `-c Release`? [Shameless plugging a blog post](https://garcia.in/posts/2021/pitfalls-of-unoptimized-nuget-packages/) on this exact situation that might give some context.

Update: I checked and 3.0.0 was compiled with optimizations.

**Comment by mantasaudickas** [comment]
Packages should be optimized now.
https://www.nuget.org/packages/Serilog.Sinks.Logz.Io/5.0.0
https://www.nuget.org/packages/Serilog.Sinks.Http.LogzIo/2.0.0

**Comment by bruno-garcia** [comment]
Seems like version 5.1.0 is still not optimized
/Users/bruno/.nuget/packages/unoptimizedassemblydetector/0.1.1/build/UnoptimizedAssemblyDetector.targets(14,5): warning : Unoptimized assembly detected: 'Serilog.Sinks.Logz.Io.dll' at /Users/bruno/.nuget/packages/serilog.sinks.logz.io/5.1.0/lib/net5.0/Serilog.Sinks.Logz.Io.dll [/Users/bruno/git/nuget-trends/src/NuGetTrends.Scheduler/NuGetTrends.Scheduler.csproj]

**Comment by mantasaudickas** [comment]
Sorry about that, should improve my release process a bit :)
Latest one (6.0.0) should be optimized again.
