### ISSUE TITLE
Add Serilog Sink icon to Serilog.Sinks.Http.LogzIo NuGet package

### ISSUE THREAD

**Issue by augustoproiete** [serilog-contrib/Serilog.Sinks.Http.LogzIo#21]
The `Serilog.Sinks.Http.LogzIo` NuGet package doesn't yet have an icon.

[![image](https://user-images.githubusercontent.com/177608/132099392-9d91a6a2-a9aa-4c20-a7f4-69b271ff87ef.png)](https://www.nuget.org/packages/Serilog.Sinks.Http.LogzIo/1.3.0)

I suggest using the standard icon for sinks:

![serilog standard sink icon](https://cdn.jsdelivr.net/gh/serilog-contrib/brand/logo/sink/serilog-sink-nuget.png)

---

More details: https://github.com/serilog-contrib/brand

**Comment by mantasaudickas** [comment]
Icon is now added to packages:
- https://www.nuget.org/packages/Serilog.Sinks.Logz.Io/5.0.0
- https://www.nuget.org/packages/Serilog.Sinks.Http.LogzIo/2.0.0
